name: C/C++ CI
env:
  SLOW_TESTS: 1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-devel:
    name: Build in Developer Mode
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install-deps
      run: sudo apt -y install ragel libev-dev liburcu-dev libsodium-dev libunwind8-dev libmaxminddb-dev libsocket6-perl libio-socket-inet6-perl libwww-perl libhttp-daemon-perl libnet-dns-perl
    - name: autoreconf
      run: autoreconf -vif
    - name: configure
      run: ./configure --enable-developer
    - name: make
      run: make
    - name: make check
      run: make check V=1
#    - name: make distcheck
#      run: make distcheck
